"""empty message

Revision ID: cae0979858c5
Revises: 6989ebac8038
Create Date: 2025-10-21 22:24:42.534192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae0979858c5'
down_revision = '6989ebac8038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songName', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('albumFrom', sa.String(length=100), nullable=False),
    sa.Column('audio', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['albumFrom'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
